### ISSUE TITLE
[NEW] A /tb add <value> command

### ISSUE THREAD

**Issue by YKDZ** [Vanderis-Dev/ThirstBarOld#1]
Add a command that can add third value to make it compatible with the consumables plug-in like MMOItems.

**Comment by HiImSunny** [comment]
We have add that command to the plugin on version 1.2, you can download it from here: https://www.spigotmc.org/resources/1-9-1-17-%E2%9A%A1-thirst-bar-%E2%9A%A1-add-thirst-unit-for-player-%E2%AD%90-placeholderapi-support.96845/download?version=423674
